# -*- coding: utf-8 -*-
"""BL2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OssrXIgFRMLyiOQeGNiUFPMVjiPHYTcI
"""

#!pip install request
#!pip install notebook
#!pip install gspread
#!pip install oauth2client
#!pip install gspread_dataframe

import pandas as pd
import numpy as np
import gspread
import os
import re
from google.oauth2 import service_account
from oauth2client.service_account import ServiceAccountCredentials


# Set option to display all columns
pd.set_option('display.max_columns', None)

from google.colab import drive
import json

# This will prompt for authorization
#drive.mount('/content/drive')


service_account_info = json.loads(os.environ['BL_SERVICE_ACCOUNT'])

# Update this path based on where the file sits in your Drive
#file_path = '/content/drive/My Drive/BL 2026/bl-reporting-d54e1fc60065.json'

#with open(file_path, 'r') as f:
#    data = json.load(f)

# Verify the data loaded
#print(data)

def remove_whitespace(df):
    """
    Remove leading and trailing whitepaces from all strings in a DataFrame.

    Parameters:
    - df (DataFrame): Input DataFrame

    Returns:
    - DataFrame: DataFrame with leading and trailing whitespaces removed from strings
    """
    return df.applymap(lambda x: x.strip() if isinstance(x,str) else x)

from oauth2client.service_account import ServiceAccountCredentials
import gspread

scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive"
]

#creds = ServiceAccountCredentials.from_json_keyfile_name(
#    "/content/drive/MyDrive/BL 2026/bl-reporting-d54e1fc60065.json",
#    scope
#)


creds = ServiceAccountCredentials.from_json_keyfile_dict(service_account_info, scopes=scope)

client = gspread.authorize(creds)

spreadsheet = client.open_by_url(
    "https://docs.google.com/spreadsheets/d/1GJGob7hlQeJqYv-CwhGoDYPJ-F4mZ-RXvHxpOnftQDU/edit"
)

import requests

#construct the full URL
url = "https://api.brushfire.com/events/626836/data?type=Attendee&includeCancelled=false"


#define the authorization key
application_key = "cy4fn6rf8wn6hq2d"

#define
headers = {
    "Authorization": application_key,
    "Content-Type": "application/json",
    "Accept": "application/json",
    "Api-Version":"2026-03-01"
}

response = requests.get(url, headers = headers)

print("Response status code", response.status_code)
print("Response text", response.text)


# check if the request was sucessful

if response.status_code ==200:
    # Parse JSON response
    data = response.json()

#conver JSON data to DataFrame
    df = pd.DataFrame(data)

    # Display the DataFrame
    print("DataFrame head:")
    print(df.head()) #Display the first few rows of DF
else:
    # Print error message if request failed
    print("Failed to fetch data from API:", response.text)

df.info()

df2 = df[["Event Title","Order Date","Hey there! What’s your name? (First)","Hey there! What’s your name? (Last)"
          ,"Hey there! What’s your name? (Combined)","What is your email address?","What is your phone number?","Do you live at least FOUR hours' drive away from the Greater Toronto Area?",
          "What Country do you live in?","We'd like to know where you're joining us from","Province","What city do you live in?","Name of your city",
          "You indicated that you live at least 4 hours' drive away from the GTA. You qualify as an Inner Circle member and you will get free a Conference Shirt. What is your shirt size?","Are you between the ages of 17-35?",
          "What's your age range?","THAT GRL is a BL segment for ladies 17-35. Will you be attending?","Will you be coming with any children ages 17 and under?",
          "What church do you attend? (Please type the full name)","We'd like to know the name of your church","How did you hear about Balance Living Conference?",
          "We'd really love to know how you heard about BL","Finally, are you interested in volunteering at the conference?",
           "How many children are you coming with?  (Please note that child care will NOT be provided)", "Have you attended the Balance Living Women’s Conference before?",
         "We're excited to have you! Are you planning on attending In Person or Online?"]]

df2.head(20)

#df2["unique_id"] = df.apply(lambda row: f"{row['Hey there! What’s your name? (Combined)']} {['What is your email address?']}", axis=1)
df2['unique_id'] = df2['Hey there! What’s your name? (Combined)'].astype(str) + "_" + df2['What is your email address?'].astype(str)

#Drop rows where the data value is None only in the specificed columns
columns_to_check = ["Hey there! What’s your name? (First)",
                    "Hey there! What’s your name? (Last)",
                    "Hey there! What’s your name? (Combined)"]

df_cleaned = df2.dropna(subset=columns_to_check, how="all")

def remove_duplicate_customers(df):

    grouped = df.groupby("unique_id")

    # Keep the first record for each customer group
    cleaned_df = grouped.first().reset_index()

    return cleaned_df



def rm_duplicate_customers(df):
    # Drop duplicate customers based on the unique_id column
    cleaned_df = df.drop_duplicates(subset="unique_id", keep="first")

    return cleaned_df

cleaned_df = remove_duplicate_customers(df_cleaned)
#Create a separate list of duplicate customer records
duplicate_customers = df[df.duplicated(subset="Hey there! What’s your name? (Combined)", keep=False)]

cleaned_df['Order Date'] = pd.to_datetime(cleaned_df['Order Date'])
cleaned_df['Order Date'] = cleaned_df['Order Date'].dt.tz_localize('UTC')
cleaned_df['Order Date'] = cleaned_df['Order Date'].dt.tz_convert('America/New_York')
#cleaned_df['Checked in @ THURSDAY: THAT GRL'] = pd.to_datetime(cleaned_df['Checked in @ THURSDAY: THAT GRL'])
#cleaned_df['Checked in @ Inner Circle- Meet & Pray'] = pd.to_datetime(cleaned_df['Checked in @ Inner Circle- Meet & Pray'])
#cleaned_df['Checked in @ FRIDAY: BL Kick Off']= pd.to_datetime(cleaned_df['Checked in @ FRIDAY: BL Kick Off'])
#cleaned_df['Checked in @ SATURDAY: Breakfast w/ The King'] = pd.to_datetime(cleaned_df['Checked in @ SATURDAY: Breakfast w/ The King'])
#cleaned_df['Checked in @ Testing'] = pd.to_datetime(cleaned_df['Checked in @ Testing'])


# Split datetime column into date and time columns

cleaned_df['week'] = cleaned_df['Order Date'].dt.to_period('W').dt.start_time
cleaned_df["date"] = cleaned_df['Order Date'].dt.date
cleaned_df["How many children are you coming with?  (Please note that child care will NOT be provided)"] = pd.to_numeric(cleaned_df["How many children are you coming with?  (Please note that child care will NOT be provided)"], errors='coerce').fillna("")

#cleaned_df["check_in_TG"] = cleaned_df['Checked in @ THURSDAY: THAT GRL'].dt.time
#cleaned_df["check_in_IC"] = cleaned_df['Checked in @ Inner Circle- Meet & Pray'].dt.time
#cleaned_df["check_in_BL_kick"] = cleaned_df['Checked in @ FRIDAY: BL Kick Off'].dt.time
#cleaned_df["check_in_breakfast"] = cleaned_df['Checked in @ SATURDAY: Breakfast w/ The King'].dt.time
#cleaned_df["check_in_testing"] = cleaned_df['Checked in @ Testing'].dt.time
# Round the time to the nearest hour

cleaned_df["date"] = cleaned_df["date"].astype(str)
#cleaned_df["check_in_TG"] = cleaned_df["check_in_TG"].astype(str)
#cleaned_df["check_in_IC"] = cleaned_df["check_in_IC"].astype(str)
#cleaned_df["check_in_BL_kick"] = cleaned_df["check_in_BL_kick"].astype(str)
#cleaned_df["check_in_breakfast"] = cleaned_df["check_in_breakfast"].astype(str)
#cleaned_df["check_in_testing"] = cleaned_df["check_in_testing"].astype(str)
cleaned_df['Order Date'] = cleaned_df['Order Date'].astype(str)
cleaned_df['week'] = cleaned_df['week'].astype(str)

#cleaned_df['Checked in @ THURSDAY: THAT GRL'] = cleaned_df['Checked in @ THURSDAY: THAT GRL'].astype(str)
#cleaned_df['Checked in @ Inner Circle- Meet & Pray'] = cleaned_df['Checked in @ Inner Circle- Meet & Pray'].astype(str)
#cleaned_df['Checked in @ FRIDAY: BL Kick Off']= cleaned_df['Checked in @ FRIDAY: BL Kick Off'].astype(str)
#cleaned_df['Checked in @ SATURDAY: Breakfast w/ The King'] = cleaned_df['Checked in @ SATURDAY: Breakfast w/ The King'].astype(str)
#cleaned_df['Checked in @ Testing'] = cleaned_df['Checked in @ Testing'].astype(str)




cleaned_df.rename(columns={
                          'Hey there! What’s your name? (First)':'First_name',
                          'Hey there! What’s your name? (Last)':'Last_name',
                          'Hey there! What’s your name? (Combined)':'Combined_name',
                          'What is your email address?':'Email',
                           'What is your phone number?':'Phone Number',
                          "Do you live at least FOUR hours' drive away from the Greater Toronto Area?":'Inner Circle Eligible',
                          'What Country do you live in?':'Country',
                         "You indicated that you live at least 4 hours' drive away from the GTA. You qualify as an Inner Circle member and you will get free a Conference Shirt. What is your shirt size":'inner_circle_t_shirt_size',
                         "We're excited to have you! Are you planning on attending In Person or Online?": "Online or In-Person"},
                 inplace=True)

cleaned_df = cleaned_df[~cleaned_df["First_name"].str.contains(r'\bTest\b', case=False)]

#cleaned_df[cleaned_df['First_name'] == 'Sandra Erica']

# List 1: substring matches in “What city do you live in?”
cities_list1 = [
    "Toronto","Vaughan","Whitby","Mississauga","Brampton","Richmond Hill","Oakville",
    "Niagara Falls","St. Catharines","Barrie","Cambridge","Other","Oshawa","Milton",
    "Burlington","Haldimand County","Brantford","Hamilton","Woodstock","Peterborough",
    "Markham","London","Kingston","St. Thomas","Belleville","Owen Sound","Welland",
    "Waterloo","Kitchener","Brant","Ajax","Orillia","Pickering","Guelph","Thorold"
    ,"Stratford","Thornhill"
]

# List 2: exact matches in “Name of your city”
cities_list2 = [
    "Bradford","Orangeville","Stoney creek","Scarborough","Mono","Caledon","Smithville",
    "Acton","Baden","Bolton","Alliston","Tillsonburg","Shelburne","Georgetown","Listowel",
    "Paris","North York","Keswick","Bowmanville","Aurora"
]

# Compile a case‑insensitive regex for List 1
pattern1 = re.compile(r"\b(" + "|".join(map(re.escape, cities_list1)) + r")\b", flags=re.IGNORECASE)

# Build the exclusion mask
mask = (
    cleaned_df["Province"].fillna("").str.strip().str.lower().isin(["ontario",""]) |
    cleaned_df["What city do you live in?"].fillna("").str.contains(pattern1) |
    cleaned_df["Name of your city"].fillna("").str.lower().isin([c.lower() for c in cities_list2])
)

# Assign Inner Circle Eligible
cleaned_df["Inner Circle Eligible"] = np.where(mask, "No", "Yes")

# 2. Open the worksheet and read existing data
worksheet = spreadsheet.worksheet("cleaned_data")
existing_records = worksheet.get_all_records()
df_existing = pd.DataFrame(existing_records)

# If df_existing is not empty, ensure it has the same unique_id column
if not df_existing.empty:
    if 'unique_id' not in df_existing.columns:
        df_existing['unique_id'] = df_existing['combined_name'].astype(str) + "_" + df_existing['email'].astype(str)

# 4. Identify new rows
if not df_existing.empty:
    new_rows_mask = ~cleaned_df['unique_id'].isin(df_existing['unique_id'])
    df_new_rows = cleaned_df[new_rows_mask].copy()
else:
    df_new_rows = cleaned_df.copy()

print(f"Found {len(df_new_rows)} new rows to add.")

# 5. Append only the new rows to the sheet
if not df_new_rows.empty:
    # Include 'unique_id' in the columns we upload
    columns_to_upload = df_new_rows.columns.tolist()  # or specify your desired column order
    rows_to_append = df_new_rows[columns_to_upload].values.tolist()
    worksheet.append_rows(rows_to_append, value_input_option='RAW')
    print("New rows appended successfully!")
else:
    print("No new rows to add.")

# FIRST TIME RUN

## Open the worksheet within the spreadsheet
#worksheet = spreadsheet.worksheet("cleaned_data")
# Write the DataFrame to the Google Sheet
#worksheet.update("A1", [cleaned_df.columns.values.tolist()] + cleaned_df.values.tolist())

